SET SERVEROUTPUT ON;

CREATE OR REPLACE TYPE RECTANGLE AS OBJECT
(
    LENGTH NUMBER,
    WIDTH NUMBER,
    MEMBER FUNCTION ENLARGE (INC NUMBER) RETURN RECTANGLE,
    MEMBER PROCEDURE DISPLAY,
    MAP MEMBER FUNCTION MEASURE RETURN NUMBER
);

/

CREATE OR REPLACE TYPE BODY RECTANGLE AS 
    MEMBER FUNCTION ENLARGE(INC NUMBER) RETURN RECTANGLE IS
    BEGIN 
        RETURN RECTANGLE(SELF.LENGTH + INC, SELF.WIDTH + INC);
    END ENLARGE;
    MEMBER PROCEDURE DISPLAY IS
    BEGIN
        dbms_output.put_line('Length: ' || LENGTH);
        dbms_output.put_line('WIDTH: ' || WIDTH);
    END DISPLAY;
    MAP MEMBER FUNCTION MEASURE RETURN NUMBER IS
    BEGIN 
        RETURN (LENGTH*WIDTH);
    END MEASURE;
END;
    
/    

DECLARE 
    R1 RECTANGLE;
    R2 RECTANGLE;
    R3 RECTANGLE;
    INC_FACTOR NUMBER := 5;
BEGIN
    R1 := RECTANGLE(3,4);
    R2 := RECTANGLE(5,7);
    R3 := R1.ENLARGE(INC_FACTOR);
    R3.DISPLAY;
    
    DBMS_OUTPUT.PUT_LINE(R1);
    
    
    
    IF(R1>R2) THEN -- CALLING MEASURE FUNCTION
        DBMS_OUTPUT.PUT_LINE('RI IS GREATER THAN R2');
        R1.DISPLAY;
    ELSE
        DBMS_OUTPUT.PUT_LINE('R2 IS GREATER THAN OR EQUALS TO R1');
        R2.DISPLAY;
    END IF;
END;













        